version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
        - "redis"
    tty: true
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/data:/data